// Core semantic enums for the LumeraAI guidance platform

export enum RuntimeState {
  BOOT = "BOOT",
  IDLE = "IDLE",
  PRE_RUN_CHECK = "PRE_RUN_CHECK",
  READY = "READY",
  ACTIVE_RUN = "ACTIVE_RUN",
  LOW_CONFIDENCE = "LOW_CONFIDENCE",
  SAFE_MODE = "SAFE_MODE",
  PAUSED = "PAUSED",
  EMERGENCY = "EMERGENCY",
  SESSION_COMPLETE = "SESSION_COMPLETE",
  SYNC_PENDING = "SYNC_PENDING",
}

export enum RunMode {
  TRACK = "TRACK",
  PARK_LOOP = "PARK_LOOP",
  PREDEFINED_ROUTE = "PREDEFINED_ROUTE",
  INTERVAL_TRAINING = "INTERVAL_TRAINING",
  ASSISTED = "ASSISTED",
}

export enum GuidanceSemanticType {
  NAV_LEFT_SLIGHT = "NAV_LEFT_SLIGHT",
  NAV_LEFT_STRONG = "NAV_LEFT_STRONG",
  NAV_RIGHT_SLIGHT = "NAV_RIGHT_SLIGHT",
  NAV_RIGHT_STRONG = "NAV_RIGHT_STRONG",
  STATUS_ON_ROUTE = "STATUS_ON_ROUTE",
  STATUS_OFF_ROUTE = "STATUS_OFF_ROUTE",
  ALERT_HAZARD = "ALERT_HAZARD",
  ALERT_SLOW_DOWN = "ALERT_SLOW_DOWN",
  ALERT_STOP = "ALERT_STOP",
  TRAINING_LAP_COMPLETE = "TRAINING_LAP_COMPLETE",
  TRAINING_INTERVAL_CHANGE = "TRAINING_INTERVAL_CHANGE",
  SYSTEM_LOW_CONFIDENCE = "SYSTEM_LOW_CONFIDENCE",
  SYSTEM_DISCONNECTED = "SYSTEM_DISCONNECTED",
}

export enum HazardType {
  OBSTACLE_STATIC = "OBSTACLE_STATIC",
  OBSTACLE_DYNAMIC = "OBSTACLE_DYNAMIC",
  SURFACE_HAZARD = "SURFACE_HAZARD",
  LANE_EDGE = "LANE_EDGE",
  STEP_DROP = "STEP_DROP",
  SURFACE_CHANGE = "SURFACE_CHANGE",
  UNKNOWN = "UNKNOWN",
}

export enum HazardSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ConfidenceBand {
  HIGH = "HIGH",
  MODERATE = "MODERATE",
  LOW = "LOW",
  CRITICAL = "CRITICAL",
}

export enum DeviceConnectionState {
  CONNECTED = "CONNECTED",
  CONNECTING = "CONNECTING",
  DEGRADED = "DEGRADED",
  DISCONNECTED = "DISCONNECTED",
}

export enum EmergencyTriggerSource {
  USER_SOS = "USER_SOS",
  WATCH_BUTTON = "WATCH_BUTTON",
  FALL_DETECTED = "FALL_DETECTED",
  POLICY_AUTO = "POLICY_AUTO",
  COMPANION_TRIGGER = "COMPANION_TRIGGER",
}

export enum SurfaceType {
  TRACK_SYNTHETIC = "TRACK_SYNTHETIC",
  TRACK_CINDER = "TRACK_CINDER",
  PATH_PAVED = "PATH_PAVED",
  PATH_GRAVEL = "PATH_GRAVEL",
  GRASS = "GRASS",
  MIXED = "MIXED",
  UNKNOWN = "UNKNOWN",
}

export enum GuidancePriority {
  EMERGENCY_STOP = 0,
  HAZARD_AVOIDANCE = 1,
  ROUTE_CORRECTION = 2,
  TURN_PREPARATION = 3,
  TRAINING_CUE = 4,
  INFORMATIONAL = 5,
}
